### PR TITLE
Feature/1481 create dialog for column names

### LINKED ISSUE #1481: Move custom column naming in desktop to separate dialog
In the context of https://github.com/datacleaner/DataCleaner/pull/1472 we made it possible to configure custom column names for a number of datastore types. Currently this is located inside the datastore configuration dialog. For some reasons it seems to better fit in a separate dialog:
It can take up a lot of space, especially when there are lots of columns, causing the datastore dialog to burst out of its window.
You are really only able to effectively configure the custom columns when all other datastore related settings have been configured.
Therefore it seems like a good idea to add another button next to Save datastore which is activated when sufficient settings to be able to preview the datastore have been configured, which opens a dialog where you can configure the custom column names and preview its effect.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #1481 

This branch is based on https://github.com/datacleaner/DataCleaner/pull/1472. But it removed the panel widget for adding the column names for Excel and CSV

The fixedwidth datastore hasn't been modified since https://github.com/datacleaner/DataCleaner/pull/1472. 

We have many branches that modifies FixedWidthDatastore and it is going to be very hard to merge them.

### CODE REVIEW

**Comment by LosD** [comment]
Comments from sprint review:
- Change "Add" to "Change"
- Make sure to update columns when other fields change (e.g. filename or separator).

**Comment by ClaudiaPHI** [comment]
image

Fixed the suggestions. Ready for testing

**Comment by jhorcicka** [comment]
Build error: No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

It builds fine on my localhost but the functionality does not work. 
column-names-01
column-names-02
column-names-03

**Comment by ClaudiaPHI** [comment]
It works for CSV and excel
The fixed width has not been implemented

**Comment by LosD** [comment]
The stalled build we sometimes see on Travis sometimes. If you restart the build, it should be fine.

**Comment by LosD** [comment]
I've restarted it

**Comment by jhorcicka** [comment]
While testing this I encountered this-issue-unrelated bug #1496. The renaming functionality works fine (with MM snapshot).

**Comment by ClaudiaPHI** [comment]
I could not reproduce bug#1496 in this branch

**Comment by LosD** [comment]
Code looks fine, but another case of reformatting whole files. _Please_ leave code you don't touch alone. No tabs->spaces, no reformatting.

**Comment by ClaudiaPHI** [comment]
I am using the eclipse formatter from DataCleaner. I can't do anything to the identation. Please merge it as it is. The tabs indentation is old.

**Comment by jhorcicka** [comment]
@losd, @ClaudiaPHI, spaces indentation was reverted back to tabs.

**Comment by LosD** [comment]
LGTM. Doesn't work yet, of course (since the functionality is not in MM yet).

**Comment by LosD** [comment]
Merge when Travis is happy

**Pull request merged**
