### PR TITLE
Increased the size of the reference data dialogs

### LINKED ISSUE #1401: Reference data dialog windows are too small
image

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #1401 

- [x] Simple string pattern 
- [x] Regular expression pattern
- [x] Datastore dictionary 

image

image

image

### CODE REVIEW

**Comment by LosD** [comment]
Does it still have some weird issues when resizing? Not that you'd need to fix it if it still does, but if it does, it would be nice to take a look at.

**Comment by LosD** [comment]
Code LGTM!

**Comment by ClaudiaPHI** [comment]
There are no weird issues when resizing.

**Comment by LosD** [comment]
Cool! Let's merge when Travis is happy.

**Pull request merged**
