### PR TITLE
Feature/1010 neo4j support

### LINKED ISSUE #1010: Add datastore and UI support for neo4j
With MetaModel 4.5.0 we will be able to easily add neo4j support.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #1010 

This PR is dependent on MM release 4.5.1. The merge is possible after MM release.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Mostly looks good, but I'm missing the Neo4j option under the file dropzone's buttons:

image

**Comment by ClaudiaPHI** [comment]
oki-doki

**Comment by ClaudiaPHI** [comment]
Added 
image

**Comment by kaspersorensen** [comment]
LGTM!

**Pull request merged**
