### PR TITLE
Added more connection parameters for making a better oracle connection

### LINKED ISSUE #355: The Oracle datastore does not allow to specify connections with service name or easy connect string
# Actual
The Oracle datastore type tab "Oracle connection" provides parameter fields for 'Hostname", "Port", "System ID (SID)", "Username" and "Password".

Oracle versions can also connect using the service name. However, the Oracle data store only works when you specify the SID.

Oracle also has the "easy connect string", which is also not supported.

#Expected
The Oracle datastore should allow connections by specifying the service name and also by specifying the easy connect string.

Oracle documentation on the easy connect string:
http://www.oracle.com/technetwork/database/enterprise-edition/oraclenetservices-neteasyconnect-133058.pdf

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #355 

Screenshot:

image

### CODE REVIEW

**Comment by drexler42** [comment]
I think the user does not need to enter service name and SID. The user typically uses the Service Name or the SID. This UI does not clearly reflect that yet. The Oracle SQL Developer tool uses a radio button to let the user choose between entering the service name or the SID (see screenshot).


2015-04-09 16_40_58-new _ select database connection

**Comment by kaspersorensen** [comment]
Good point and thx for the screenshot. Will see if I can improve.

**Comment by kaspersorensen** [comment]
Updated: 

image

**Comment by ClaudiaPHI** [comment]
Looks good to me

**Comment by drexler42** [comment]
Looks good.

**Pull request merged**
