### PR TITLE
Made visualization of compound requirements work

### PR DESCRIPTION
**Pull request by kaspersorensen**
First part of #159 - the job graph visualization part. Still the story needs ability to make/modify compound requirements somehow to be complete.

Following is a screenshot of a compound requirement (that was made "in hand" in the .analysis.xml file):

image

The compound requirement is OR based ... is that communicated in the graph? can we improve that any way?

### CODE REVIEW

**Comment by tomaszguzialek** [comment]
A? I am confused, just by looking at the screenshot, TBH...

**Comment by kaspersorensen** [comment]
Hmm yes I also think it's a bit confusing ... It makes more sense in other cases like:

```
A -> B -> C -> D -> ...
        \     /
           X
```

**Comment by kaspersorensen** [comment]
How would you ideally visualize the above scenario though? Two filters on the source table and if either of them evaluates to a particular outcome, then run the component in question ....

**Comment by tomaszguzialek** [comment]
I am getting confused by this "A?" - not really sure what this is supposed to mean. If there were "OR" instead of "A?" then it makes sense for me.

**Comment by kaspersorensen** [comment]
Ah LOL ... that 'A' is part of the icon for 'String analyzer'. It has nothing to do with this particular issue :)

**Comment by tomaszguzialek** [comment]
Oh, well... :). Anyways, we should add "OR" in the graph to notify the user that it is not "AND".

**Comment by ClaudiaPHI** [comment]
I agree with Tomasz. Maybe it's better to add a visual thing on the graph.

**Comment by kaspersorensen** [comment]
How would you do it? Should the composite requirement show up as a node/vertex on the graph?

**Comment by kaspersorensen** [comment]
Gonna merge this since it is harmless (only an improvement over previous inability to visualize at all). Please continue the discussion about the visualization on issue #159

**Pull request merged**
