### PR TITLE
OutputDataStreamBuilder convenience method addition

### PR DESCRIPTION
**Pull request by kaspersorensen**
Added a few convenience methods to easily add columns to an output data stream that are similar to other columns.

### CODE REVIEW

**Comment by tomaszguzialek** [comment]
LGTM.

**Comment by LosD** [comment]
LGTMToo

**Comment by kaspersorensen** [comment]
LGTM2 ?

**Comment by tomaszguzialek** [comment]
The failure of the "push" build seems unralated to this PR, but we the log suggest we have some race condition we should have a look someday:
```
Failed tests: 

  UsageAwareDatastoreConnectionTest.testCloseNoRaceConditions:152 null
```

**Comment by kaspersorensen** [comment]
Hmm looking at that test it seems that it is missing a Thread.join() call ... I'll check it out a bit ...

**Pull request merged**
