### PR TITLE
Do not check Excel for existing sheet if overwrite is okay

### LINKED ISSUE #1529: CreateExcelSpreadsheetAnalyzer unneeded validation
If the overwriteSheetIfExists flag is set in `CreateExcelSpreadsheetAnalyzer`, there is no need to actually open the spreadsheet. This can take a lot of time during opening jobs for no reason.

### PR DESCRIPTION
**Pull request by LosD**
Performance fix in case user has checked "overwrite sheet if exists" in CreateExcelSpreadsheetAnalyzer.

Fixes #1529

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM as I have seen it working :-D

**Comment by LosD** [comment]
I guess that means we'll need someone completely out of the loop to review :)

@jhorcicka or @arjansh can I get one of you to take a look?

**Comment by jhorcicka** [comment]
I will test it, @LosD, @arjansh.

**Comment by jhorcicka** [comment]
Tested and LGTM.

**Pull request merged**
