### PR TITLE
Feature/718 remote components setup ui

### PR DESCRIPTION
**Pull request by jhorcicka**
In DC desktop options dialog there is a new tab "remote components" where credentials can be set. Default values are read from the conf.xml file where multiple servers can be specified. GUI dialog can overwrite the first server's username and password.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Can we create a 5.0 branch to merge this into instead? I don't want to add this to the master branch this close to the 4.5 release.

**Comment by jhorcicka** [comment]
OK. I created "release/5.0" branch.

**Comment by jhorcicka** [comment]
I will use this branch for the password encoding in the conf.xml file. Please, wait with the merge...

**Comment by jakubneubauer** [comment]
Will create new PR to merge into release/5.0 branch

**Pull request closed without merging**
