### PR TITLE
thread-safe creation of shared instance of ConvertToDateTransformer

### PR DESCRIPTION
**Pull request by jakubneubauer**

### CODE REVIEW

**Comment by LosD** [comment]
Shouldn't the block also be synchronized? Otherwise you risk different threads both creating a new instance.

**Comment by jakubneubauer** [comment]
In this case it is not necessary, creating more instances doesn't harm.

**Comment by LosD** [comment]
LGTM, then (can't merge myself, silly Android app doesn't allow it)

**Comment by jakubneubauer** [comment]
no problem :-)

**Pull request merged**
