### PR TITLE
Issue #442: Made a new menu item/button for each component/result.

### LINKED ISSUE #442: Add a new tab to ResultWindow for each component that produces a result
Instead of grouping results per _component type_ we would prefer to just have a new tab for each component instance. This would mean a lot more tabs, but since the tabs are now shown vertically we can also better scale the UI here. It will relieve us from having to use the task panes that each result is currently placed in, and as such provide more screen real-estate.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #442 

Would be interested in review remarks both on code but certainly also on design. Will post some screenshots in the comments here.

__do not merge in it's current state__

Also alleviated the stretching issue for pattern finder (see #451) while it is still not fixed, only updated a bit for higher resolutions.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
image

**Comment by kaspersorensen** [comment]
image
(notice the horizontal scroll which I allowed (what do you think?) for wide result renderings).

**Comment by kaspersorensen** [comment]
The pattern finder result now has a pretty big chart...
image

**Comment by kaspersorensen** [comment]
Currently a problem: The dedup result display is typically too wide. This is a case of where it would be good to disable the horizontal scroll.

image

**Comment by kaspersorensen** [comment]
The same applies to training mode. Here we also see that the background color has changed so the existing renderer probably needs to be adjusted:

image

**Comment by kaspersorensen** [comment]
I changed the look and feel of the tabs, so that they look fine on the white background.
I also removed the horizontal scroll.

Looks good in training mode:
image

But for some reason it still looks strange with the dup. detection result. It seems that it is not fitting the result into the screen even though the horizontal scrolls are gone:

image

**Comment by kaspersorensen** [comment]
There... Now that is also fixed. I am feeling done with this story, so please review.

By now I am also happy to say that it not only fixes #442 but also #443:

Fixes #443

**Comment by ClaudiaPHI** [comment]
LGTM!

**Pull request merged**
