### PR TITLE
Add EBCDIC encodings to list

### LINKED ISSUE #1346: Make aliases for EBCDIC encodings
There are quite a few users of EBCDIC encodings, so we would like to add those to the combobox.

Unfortunately, the code pages are pretty cryptic, so stating that it's EBCDIC would be nice.

### PR DESCRIPTION
**Pull request by LosD**
This will and the (euro-supporting version of) EBCDIC encodings to the combobox, and mark them as such.

Fixes #1346

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM !

**Comment by jhorcicka** [comment]
What about IBM500? https://www.ibm.com/support/knowledgecenter/SSB23S_1.1.0.12/gtpa2/char51.html

**Comment by LosD** [comment]
IBM01147 _is_ IBM500, but with support for the Euro character.

**Comment by LosD** [comment]
Sorry, IBM01148

**Comment by LosD** [comment]
Not sure if we'll need to support IBM500 explicitly, but I'd add it if we get complaints.

**Comment by jhorcicka** [comment]
OK, thanks for clarification.

**Pull request merged**
