### PR TITLE
A few updates to IDEA codestyle file

### PR DESCRIPTION
**Pull request by LosD**
This tweaks some settings and re-enables JavaDoc formatting.

@jhorcicka Can I get you to check this when you have the time?

### CODE REVIEW

**Comment by jhorcicka** [comment]
I updated the xml configuration in IDEA (code style scheme) and tried to reformat the whole project => no changes. @LosD, should I check something else?

**Comment by LosD** [comment]
No changes at all sounds weird. Did you import the configuration _and_ change to the imported profile?

**Comment by jhorcicka** [comment]
I used the option to overwrite current scheme. I tried it again and now it worked (many changes).

**Comment by jhorcicka** [comment]
I briefly went through all the changes and I agree with all of them but one related to enums. 

This: 
```
    enum A {
        ONE, 
        TWO, 
        THREE
    }

    enum B {
        ONE("one", 1), 
        TWO("two", 2);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }

    enum C {
        VERY_LONG_NAME_ONE("very_long_name_one", 1), VERY_LONG_NAME_TWO("very_long_name_two", 2), VERY_LONG_NAME_THREE("very_long_name_three", 3);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }
```
is reformatted to
```
    enum A {
        ONE, TWO, THREE
    }

    enum B {
        ONE("one", 1), TWO("two", 2);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }

    enum C {
        VERY_LONG_NAME_ONE("very_long_name_one", 1), VERY_LONG_NAME_TWO("very_long_name_two", 2),
        VERY_LONG_NAME_THREE("very_long_name_three", 3);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }
```

I discussed that with @arjansh who tried that in Eclipse. The behaviour is different for C. Personally I would like to have all the values on separate lines which can be set in both Eclipse and IDEA GUI (I don't know about that XML). 

What do you think about it, @LosD?

**Comment by LosD** [comment]
I remember I had a discussion with @arjansh on that exactly. I just don't remember the conclusion :)

**Comment by arjansh** [comment]
@LosD In Eclipse using the DataCleaner formatting rules for Eclipse,, "Enum C" is reformatted with all the values on separate lines, which is to my liking.

**Comment by LosD** [comment]
Hmmmm... I _think_ we agreed we would only do that for simple enums (no arguments or comments). But I might remember wrongly

**Comment by arjansh** [comment]
So, should I change it for Eclipse?

**Comment by LosD** [comment]
Nono, I'll fix it in my end. I think a simple change to "chop down if long" should do it.

**Comment by LosD** [comment]
@jhorcicka Could you check again at some point?

**Comment by jhorcicka** [comment]
Now it looks like this: 
```
    enum A {
        ONE, TWO, THREE
    }

    enum B {
        ONE("one", 1), TWO("two", 2);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }

    enum C {
        VERY_LONG_NAME_ONE("very_long_name_one", 1),
        VERY_LONG_NAME_TWO("very_long_name_two", 2),
        VERY_LONG_NAME_THREE("very_long_name_three", 3);

        private String _s;
        private int _i;

        B(String s, int i) {
            _s = s;
            _i = i;
        }
    }
```

Which is fine with me. Can I merge it then?

**Comment by jhorcicka** [comment]
LGTM.

**Pull request merged**
