### PR TITLE
Issue #971: Sanitize configuration elements

### LINKED ISSUE #971: Remove (default) storage provider and task runner from (default) conf.xml
Transfering conf.xml files from machine to machine or environment to environment (e.g. from desktop to monitor, or from desktop to Hadoop). The most common reason for this (IMO) is that the task runner and storage provider (and in some cases descriptor provider) defaults are not the same in these environments. By removing these elements from conf.xml we can in most cases rather provide the default from the particular environment's codebase. But of course still offering the ability to specify them in XML which would override the default.

For background, here's how the things are normally configured/expected:

 * Task runner
  * desktop: Multithreaded with 30 threads
  * spark: Singlethreaded (because Spark handles the parallelism)
  * monitor: SharedTaskRunner (delegates to a shared thread pool for all tenants)
 * Storage provider
  * desktop: Combined berkeley DB (for collections) and in-memory (for row-annotations) storage 
  * spark: In-memory everything
  * monitor: in-memory everything
 * Descriptor provider
  * desktop: Classpath scanner specified
  * spark: Classpath scanner specified
  * monitor: SharedDescriptorProvider (delegates to a shared instance for all tenants)

### PR DESCRIPTION
**Pull request by kaspersorensen**
Trying to make the descriptor provider, task runner and storage provider optional configuration elements with good defaults.

Fixes #971

### CODE REVIEW

**Comment by LosD** [comment]
LGTM. Has it been manually tested in affected environments?

**Comment by kaspersorensen** [comment]
To be honest: Only manually tested in desktop environment.

**Comment by kaspersorensen** [comment]
I will try it out in monitor now.

**Comment by kaspersorensen** [comment]
Works well in DC monitor. Trying also Spark on bigdatavm.

**Comment by kaspersorensen** [comment]
Totally works :)

**Comment by LosD** [comment]
:+1:

**Pull request merged**
