### PR TITLE
Convert2java: HtmlRenderer, CompositeBodyElement and BooleanAnalyzer res

### PR DESCRIPTION
**Pull request by davkrause**
These conversions mean that I can build much more of DC without Scala
and that I can exclude scala from my dependencies when depending on
datacleaner-html-rendering

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Generally this change looks fine with me but please check the build failure.

**Comment by kaspersorensen** [comment]
Looking into html-rendering module a bit. It would be nice to get rid of scala entirely here. As you mention, it adds a transitive dependency to something that is rather core.

**Comment by davkrause** [comment]
OK, I work on it

**Comment by kaspersorensen** [comment]
Nice work and thank you @davkrause.

**Pull request merged**
