### PR TITLE
Feature/documentation update for 4.0

### PR DESCRIPTION
**Pull request by kaspersorensen**
Updates to the docs to be visually in line with 4.0 styles.
Still the documentation text/wording is not correct/updated.

### CODE REVIEW

**Comment by LosD** [comment]
Seems to have made Travis angry, for some strange reason only on JDK 7, in what seems to be a completely unrelated test, AnalyzerResultFutureTest.testMultiThreadedListenerScenario()

(The failing test being a test of threaded code could mean we have some randomness there)

**Comment by kaspersorensen** [comment]
I'll take a look at the test, but yes it must be unrelated so please do not consider it part of this PR.

**Comment by LosD** [comment]
Well, there's not much to review but the images seems correct :)

**Comment by kaspersorensen** [comment]
OK I was just hoping someone else would click merge, but now I'm gonna do it :D

**Pull request merged**
