### PR TITLE
Feature/remote transformers remote enums

### LINKED ISSUE #683: Support for remote transformer enumeration if enum class not available on desktop
In case a transformer is published on the server and this tranformer uses some custom "enum", this enum class will be not available on the client side (desktop). The enum values are already part of the remote transformer description that is obtained by the desktop. Now we need to make use of this information on the Desktop side and provide appropriate GUI for it.

### PR DESCRIPTION
**Pull request by jakubneubauer**
fixes #683

### CODE REVIEW

**Comment by kaspersorensen** [comment]
LGTM

**Comment by kaspersorensen** [comment]
build failure is unrelated btw... but on my radar, just committed https://github.com/datacleaner/DataCleaner/commit/8c93887d4dd0f1d55c4dafd15e8407b61a97682d to learn more about it because it's seems to happen once in a while.

**Comment by jakubneubauer** [comment]
Sorry, I merged different branch #686 into this branch. So, this PR should be resolved only after #686.

**Comment by LosD** [comment]
#686 is merged, I guess we can merge this now?

**Comment by jakubneubauer** [comment]
Yes, we can merge

**Comment by jakubneubauer** [comment]
Oh no, Travis complains

**Comment by LosD** [comment]
It's not the unrelated error @kaspersorensen mentioned?

**Comment by LosD** [comment]
No, doesn't seem like it, it's in the DefaultEnumMatcherTest:
```
Tests run: 7, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 0.034 sec <<< FAILURE! - in org.datacleaner.util.DefaultEnumMatcherTest
testSuggestByAlias(org.datacleaner.util.DefaultEnumMatcherTest)  Time elapsed: 0.006 sec  <<< FAILURE!
```

**Comment by jakubneubauer** [comment]
ok, now it is ready I believe

**Comment by LosD** [comment]
Travis agrees. Let's merge! :)

**Pull request merged**
