### PR TITLE
Bug/minor tweaks to melon jobs

### PR DESCRIPTION
**Pull request by kaspersorensen**
Once #597 is merged then this PR adds a few more tweaks/improvements:

 * Edge rendering of transformations within sub jobs
 * Fixed query optimization in sub jobs

### CODE REVIEW

**Comment by LosD** [comment]
Gotta love the "minor tweaks" tag for an addendum to a PR half its size :)

**Comment by LosD** [comment]
Ahhhh... It's of course _including_ the other PR.

Will wait with review until we merge the other one.

**Comment by kaspersorensen** [comment]
Merged in master, now the diff is a lot smaller :-)

**Comment by kaspersorensen** [comment]
And to help the reviewer: The RowProcessingQueryOptimizerImpl class is exactly the same as the "old" RowProcessingQueryOptimizer class. It's just that it was made into an interface + an implementation.

**Comment by kaspersorensen** [comment]
Hmm I cannot reproduce the build failure. Thinking it must have been a Travis glitch.

**Comment by tomaszguzialek** [comment]
Build fixed (by restarting).

**Pull request merged**
