### PR TITLE
Datahub connector minor improvements

### PR DESCRIPTION
**Pull request by MennoB**
This branch contains the requested improvements to the datahub xml configuration persistance. Also added datahub datasource to the existing xml configuration test, for good measure.

### CODE REVIEW

**Comment by MennoB** [comment]
Hm, on second thought, maybe wait a bit until @hdrexler and @HettyK  are done with their tenant service changes, so that I can merge those with these changes as well.

**Comment by kaspersorensen** [comment]
To me this PR looks 100% OK, but if you want to wait for @hdrexler and @HettyK then I won't click the "Merge" button :-) But feel free to do so when you have sync'ed!

**Comment by MennoB** [comment]
Thanks! Will do.

**Comment by kaspersorensen** [comment]
This branch is now outdated - do you want to update it or is it no longer relevant?

**Comment by MennoB** [comment]
That is as expected. Now that the tenant service stuff has been merged in the master, I can now properly integrate these changes with those.

**Comment by HettyK** [comment]
Hi Menno,
I did some additional testing with this branch (creating datastore, running job etc). All works fine.

**Comment by MennoB** [comment]
Thanks! Will merge.

**Pull request merged**
