### PR TITLE
Changed the css so that all alerts are visible to edit

### LINKED ISSUE #1051: DC monitor - cannot edit all the alerts
image

The UI doesn't give access to all the alerts of a job

image

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #1051  

image

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
image

**Comment by kaspersorensen** [comment]
Good touch to move it down. +1 from me.
Was it tested in the usual browsers? (asking because I don't know that well "inline-table")

**Comment by LosD** [comment]
inline-table is supported in all major browsers (the usual suspect has supported it since version 8): https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by ClaudiaPHI** [comment]
IE : 

image

Firefox: 

image

**Comment by ClaudiaPHI** [comment]
The weird "execute" button has nothing to do with "inline-table" css change. I tried with the original war file and the "Execute" button is still weird. 

image

**Comment by ClaudiaPHI** [comment]
css button line-height:1.2 em; 
Chrome: 

image

Firefox: 

image


IE 11:

image

**Comment by ClaudiaPHI** [comment]
Also fixes #1059

**Comment by kaspersorensen** [comment]
Looks good to me!

**Comment by ClaudiaPHI** [comment]
I have tested all the screens. it looks nice!

**Comment by LosD** [comment]
YEAH!

**Comment by ClaudiaPHI** [comment]
Nobody want to merge  ?

**Pull request merged**
