### PR TITLE
Bug/1268 transfer scala to java

### LINKED ISSUE #1268: Scala deserialization exception for a job ran on Hadoop
I have ran the following job with Scatter plotter which is written in Scala: 

``` 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job xmlns="http://eobjects.org/analyzerbeans/job/1.0">
    <job-metadata>
        <job-description>Created with DataCleaner Enterprise edition 5.0-SNAPSHOT</job-description>
        <author>claudiap</author>
        <updated-date>2016-03-31+02:00</updated-date>
        <metadata-properties>
            <property name="CoordinatesX.datacleaner.customers.csv">40</property>
            <property name="CoordinatesY.datacleaner.customers.csv">40</property>
        </metadata-properties>
    </job-metadata>
    <source>
        <data-context ref="customers.csv_2"/>
        <columns>
            <column id="col_id" path="id" type="STRING"/>
            <column id="col_given_name" path="given_name" type="STRING"/>
            <column id="col_family_name" path="family_name" type="STRING"/>
            <column id="col_company" path="company" type="STRING"/>
            <column id="col_address_line" path="address_line" type="STRING"/>
            <column id="col_post_code" path="post_code" type="STRING"/>
            <column id="col_city" path="city" type="STRING"/>
            <column id="col_country" path="country" type="STRING"/>
            <column id="col_email" path="email" type="STRING"/>
            <column id="col_birthdate" path="birthdate" type="STRING"/>
            <column id="col_gender" path="gender" type="STRING"/>
            <column id="col_job_title" path="job_title" type="STRING"/>
            <column id="col_income_amount" path="income_amount" type="STRING"/>
            <column id="col_income_currency" path="income_currency" type="STRING"/>
        </columns>
    </source>
    <transformation>
        <transformer name="Birthdate as date">
            <descriptor ref="Convert to date"/>
            <metadata-properties>
                <property name="CoordinatesX">360</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties>
                <property name="Time zone" value="Europe/Berlin"/>
                <property name="Null replacement" value="&lt;null&gt;"/>
                <property name="Date masks" value="[yyyy-MM-dd HH:mm:ss.S,yyyy-MM-dd HH:mm:ss,yyyy-MM-dd HH:mm,yyyyMMddHHmmssZ,yyMMddHHmmssZ,yyyy-MM-dd,yyyy.MM.dd,yyyy/MM/dd,dd-MM-yyyy,dd.MM.yyyy,dd/MM/yyyy,MM-dd-yyyy,MM.dd.yyyy,MM/dd/yyyy]"/>
            </properties>
            <input ref="col_birthdate"/>
            <output id="col_birthdateasdate" name="birthdate (as date)"/>
        </transformer>
        <transformer>
            <descriptor ref="Date to age"/>
            <metadata-properties>
                <property name="CoordinatesX">520</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties/>
            <input ref="col_birthdateasdate"/>
            <output id="col_ageindays" name="Age in days"/>
            <output id="col_ageinyears" name="Age in years"/>
        </transformer>
        <transformer name="Money amount as number">
            <descriptor ref="Convert to number"/>
            <metadata-properties>
                <property name="CoordinatesX">520</property>
                <property name="CoordinatesY">200</property>
            </metadata-properties>
            <properties>
                <property name="Decimal separator" value="&amp;#44;"/>
                <property name="Minus sign" value="-"/>
                <property name="Null replacement" value="&lt;null&gt;"/>
                <property name="Thousand separator" value="."/>
            </properties>
            <input ref="col_income_amount"/>
            <output id="col_income_amountasnumber" name="income_amount (as number)"/>
        </transformer>
    </transformation>
    <analysis>
        <analyzer name="Age in years vs income_amount (as number)">
            <descriptor ref="Scatter plot"/>
            <metadata-properties>
                <property name="CoordinatesX">680</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties/>
            <input ref="col_gender" name="Group column"/>
            <input ref="col_ageinyears" name="Variable1"/>
            <input ref="col_income_amountasnumber" name="Variable2"/>
        </analyzer>
    </analysis>
</job>

 ``` 

The **exception** while trying to open the  result file: 

```
Unexpected error!
 
Message:
    java.io.InvalidClassException: scala.collection.immutable.$colon$colon; local class incompatible: stream classdesc serialVersionUID = -8476791151983527571, local class serialVersionUID = 509929039250432923
Level:
    SEVERE
Stack Trace:
scala.collection.immutable.$colon$colon; local class incompatible: stream classdesc serialVersionUID = -8476791151983527571, local class serialVersionUID = 509929039250432923
    java.io.ObjectStreamClass.initNonProxy(Unknown Source)
    java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
    java.io.ObjectInputStream.readClassDesc(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.defaultReadFields(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.readObject(Unknown Source)
    java.util.HashMap.readObject(Unknown Source)
    sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    java.lang.reflect.Method.invoke(Unknown Source)
    java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.defaultReadFields(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.readObject(Unknown Source)
    org.datacleaner.actions.OpenAnalysisJobActionListener.openAnalysisResult(OpenAnalysisJobActionListener.java:144)
    
```
The problem seems to be that Hadoop is using other version of Scala.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes  #1268 

- Transferred the visualization analyzers results code from Scala to Java.
- Wizards work on Hadoop.  
- Hadoop returns results for all the visualization analyzers. 
- Due to compilation error 2 analyzers have been transferred to Java 
- The old html and swing renderers  have been kept and the new ones have end with the word "revised"

### CODE REVIEW

**Comment by LosD** [comment]
It surprises me that you had to change the analyzers to Java, but if so, that's okay.

Because this is something we'll have to live with for a long time, I'll be pretty annoying (to both of you) and ask for @kaspersorensen's comments. Sorry about that.

@kaspersorensen, do we have a better backwards loading-of-job compatibility than to keep two versions of results (and worse, the renderers), and what have we traditionally kept as the naming strategy? `Revised`, `2` and so on is pretty nasty, but I can't really think of anything better :(

**Comment by LosD** [comment]
(@kaspersorensen see also original PR here: #1294)

**Comment by ClaudiaPHI** [comment]
I am looking forward to any suggestions for improvements.

**Comment by ClaudiaPHI** [comment]
I do remember @kaspersorensen wanted to get rid of the scala code at some point.

**Comment by ClaudiaPHI** [comment]
Small comment: 

One of the reasons I had to transfer scala analyzers to java is that once I added a java folder to the project, the scala classes were not visible anymore in the other projects at compilation. 

Ex: ScatterAnalyzer which is used in the commercial eddition for the exploratory wizard.

**Comment by kaspersorensen** [comment]
Sorry for not responding, the mention got lost in the mail inbetween 100s of other things :)

We don't have a _good_ way of migrating from one result type to another. A few times we've done some crazy tricks to pull something like that off. I'm thinking especially about the renamed and moved results which we have a bit of special handling of in `ChangeAwareObjectInputStream`. It can also be combined with hooking into the `readObject` and `writeObject` optional methods in the serialization API. But it's not an easy route to go down so caution is advised.

**Comment by kaspersorensen** [comment]
In this case I'd probably recommend making an interface for each result type, which should be implemented by both the old and the new result. And then make the renderers work on the interface, not the implementation.

**Comment by LosD** [comment]
Unfortunately, I'm not sure that `UsageAwareObjectInputStream` helps that much with the naming, as there is a new class taking the renamed class' name. At least some sort of logic is needed to determine which one it is.

**Comment by kaspersorensen** [comment]
Ah right ... Can it be avoided to reuse the same class name then?

In another setting I just saw that stuff blow up in our face (https://issues.apache.org/jira/browse/METAMODEL-241) when trying to determine if the old class (an enum) or the new class (a normal class) is being deserialized. It's really dirty.

**Comment by LosD** [comment]
Reflection. It's wonderful! :)

Well, the main reason to try this route was to avoid an ugly new name in the first place, but combined with your other suggestion, it may be a little less nasty:
interface `DensityAnalyzerResult`
legacy class `ScalaDensityAnalyzerResult`
new class `JavaDensityAnalyzerResult`

The classes would still have stupid names, but the interface alleviates that in most cases.

And since the interface can never be instantiated, we _know_ that a DensityAnalyzerResult being deserialized must be the Scala class.

Possible problems: Since we're defining the interface in the interface (well, duh :)), we will probably need a conversion of the internal data to provide it. I'm not sure if that nasty Scala constructor-is-the-body pattern will throw a wrench in that idea.

**Comment by LosD** [comment]
Playing around, and the biggest wrench seems to come from the Tuple2. If we want to rid ourselves of the Scala in the results, we can't really use that. Currently using commons lang3 Pair<Integer, Integer> as replacement. @ClaudiaPHI used java.awt.Point, which seems like too much of a stretch (using floats and being part of the graphics API more or less rules it out).

The only problem is performance; the Java conversion methods doesn't expect to convert the actual members as well (which makes sense), so I need to copy the entire collection upon reading.

**Comment by LosD** [comment]
Please see #1305 for the my approach.

**Comment by ClaudiaPHI** [comment]
I guess when can close this PR

**Comment by LosD** [comment]
Yes, but don't delete the branch. We may want to convert the rest a little later

**Comment by ClaudiaPHI** [comment]
ok.

**Pull request closed without merging**
