### PR TITLE
Feature/1069 update storage provider defaults

### LINKED ISSUE #1069: Update defaults settings for InMemoryStorageProvider
Right now the default setttings storage provider is to use max. 500 sample sets with max 500 sample records each.

We would like to change the default to allow for more sets, potentially with fewer sample records, to allow at least previewing more of the "long tail" cases in a typical DQ analysis.

See ```InMemoryStorageProvider```

New defaults should be to have default max 1000 sample sets with max 150. records each.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Fixes #1069

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM!

**Comment by LosD** [comment]
Not new, but a bit too magic-numbery for my tastes

**Comment by kaspersorensen** [comment]
You mean the math stuff for the one-argument constructor? Or all of it?

**Comment by LosD** [comment]
Mostly the repeating numbers in the two contructors, but all magic numbers should preferably be declared constants.

**Comment by kaspersorensen** [comment]
Added constants now. Obviously that's not possible in the .xsd, but now they're at least available in the java code.

**Comment by LosD** [comment]
LGTM

**Pull request merged**
