### PR TITLE
Issue #1184: Implemented various improvements to DataCloud dialog

### PR DESCRIPTION
**Pull request by kaspersorensen**
My proposal for #1184

image

### CODE REVIEW

**Comment by LosD** [comment]
That is.... Extremely large.

**Comment by kaspersorensen** [comment]
Hmm ... You're right. I struggled a lot with the group layout. Maybe @khouzvicka can help a bit.
And maybe we can do a horizontal login layout, a la 
http://bootsnipp.com/img/screenshots/5f6fa4e37c9eb93e3d3b7ba7dba5ec6711007297.jpeg

**Comment by kaspersorensen** [comment]
OK and maybe the image should only be half as big ;-) And maybe the text should be less too ...

**Comment by LosD** [comment]
:)

**Comment by khouzvicka** [comment]
datacleaner welcome version 8

New Version of dialog.
@LosD @kaspersorensen 
It is ok from your side?

**Comment by LosD** [comment]
Looks good to me! :)

Maybe bit on the large size, but that's fine.

**Comment by kaspersorensen** [comment]
Looks very nice. Good to merge now - maybe we shall shorten the text to a one-liner and have a "read more" link, but this is a very good start!

**Comment by khouzvicka** [comment]
@kaspersorensen When you have better version of text, please change it. It is better finish it completely.

**Comment by khouzvicka** [comment]
@kaspersorensen I would like to merge it. Changes in text will be do after that.

**Comment by kaspersorensen** [comment]
Yes, merge when Travis is green

**Comment by khouzvicka** [comment]
@kaspersorensen  Travis is green. :-)

**Pull request merged**
