### PR TITLE
Bug #867 Nicer remote components tab

### PR DESCRIPTION
**Pull request by jhorcicka**
OptionsDialog, remote components tab. Description text is spread to the full width of the panel. In the code, methods for creating the tab were moved into a separate private class in the same file.

### CODE REVIEW

**Comment by kaspersorensen** [comment]
A process note - In cases like this it always helps with a screenshot on the PR, allowing people to quickly review the actual UI change from a user perspective.

**Comment by jhorcicka** [comment]
Old version:
oldversion

New version:
newversion

**Comment by kaspersorensen** [comment]
The layout change looks good to me. We should probably look more at the actual text in there too - I think it gives me a bit too technical feeling right now and I would rather focus the text on what I as a user will get by entering my credentials here - but that can wait till we get closer to launching this so that messaging is convered in a cohesive way.

+1

**Comment by jhorcicka** [comment]
I fully agree. For now it enables remote components but I guess more functionality is coming.

**Comment by jakubneubauer** [comment]
reviewed, fixes #867

**Pull request merged**
