### PR TITLE
#1435: IN operator support in CompareFilter.

### PR DESCRIPTION
**Pull request by jhorcicka**
Solves #1435. 

IN operator was added in CompareFilter. 

in_operator

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM! Tested and it works fine!

**Comment by LosD** [comment]
How well does this work with query optimization for SQL databases?

**Comment by LosD** [comment]
(added to my testing schedule)

**Comment by LosD** [comment]
Perfect. From SQL Server Profiler trace of a run on Danish address table I had laying around:
`SELECT (long list of columns ...) WHERE dbo."addresser"."postnr" IN ('2700' , '2900')`

**Comment by LosD** [comment]
LGTM!

**Pull request merged**
