### PR TITLE
improved the looks of the dropzone

### LINKED ISSUE #646: Improve file dropzone to allow selection of HDFS files
Add a button next to the "(or click to browse)" button inside the dropzone to allow selecting/entering a HDFS resource path.

 - [x] The button should feature a small Hadoop (elefant) icon.
 - [x] Label should be "Select Hadoop HDFS file".
 - [x] The existing button should be relabeled to "Click to browse".
 - [x] When clicking the button we want to show the HDFS resource selector widget. Preferably inside the dropzone somehow - maybe replacing the position of the buttons.
 - [x] Once selected the automagic creation of datastore should function like/similar to selecting a normal local file.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #646 
Improvements for this branch https://github.com/datacleaner/DataCleaner/pull/699 

screen shot 2015-09-28 at 1 29 29 pm

screen shot 2015-09-28 at 1 29 42 pm

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Looks good to me. Feel free to merge when Travis is green.

**Comment by ClaudiaPHI** [comment]
Travis better agree :-D

**Comment by LosD** [comment]
Another too late comment (we're good at this!): It's "The HDFS file does not exist" (Capital HDFS and exists->exist).

**Comment by ClaudiaPHI** [comment]
It's on master already.

**Comment by LosD** [comment]
New PR?

**Comment by LosD** [comment]
(This is one of those few that doesn't really need a PR, doing the edit in master should be okay)

**Comment by ClaudiaPHI** [comment]
ok. In a bit.

**Comment by ClaudiaPHI** [comment]
It has been corrected. 

screen shot 2015-09-29 at 12 28 40 pm

**Comment by LosD** [comment]
:+1:

**Pull request merged**
