### PR TITLE
Added proxy configuration when DataHub runs CAS behind a proxy

### PR DESCRIPTION
**Pull request by drexler42**
Please review & merge if OK. 

@LosD : If you need more info, shout! We can ask one of our team to do the first review.

### CODE REVIEW

**Comment by LosD** [comment]
LGTM, but let's also have one of your team members review it, some knowledge about the DH connection and how it is used is probably an advantage.

**Comment by drexler42** [comment]
Okay. Will ask review by 1 of our team. Found a problem that needs fixing...

**Comment by ClaudiaPHI** [comment]
+1

**Comment by LosD** [comment]
How is this coming along?

**Comment by LosD** [comment]
@drexler42 can we merge this, or is there still reviewing/fixes to be made?

**Pull request closed without merging**
