### PR TITLE
Fixes #1009: Replaces CE blurb with links to info or update

### LINKED ISSUE #1009: Notify user about software update available
In the current call to the DC ping service we get back the latest version number too. We should do a check to see if there is a need for the user to update his software - and inform him about it.

### PR DESCRIPTION
**Pull request by kaspersorensen**
This PR adds notifications in the status bar about software updates available. When you click, you get redirected the CE website (https://datacleaner.github.io) - either the front page (when no update is available) or the downloads page (when an update is available).

### CODE REVIEW

**Comment by LosD** [comment]
Code mostly LGTM.

Not a big fan of the hardcoded URLs, though. It makes testing and special deployments (e.g. local mirrors) harder, and it's pretty bad style, IMHO. At least an environment variable or Java property would be a good idea.

**Comment by kaspersorensen** [comment]
Fixed

**Comment by kaspersorensen** [comment]
OMG, checkstyle, you're killing me. Hang on while I reformat a line of code.

**Comment by LosD** [comment]
Super!

I'll try it out tonight (maaaaybe tomorrow, I have a long workday today)

And you do win the "commit message of the year" award :)

**Comment by kaspersorensen** [comment]
;-) I'm fine with a merge-commit instead

**Comment by LosD** [comment]
Oh man, I completely forgot about testing this. I gather you got tired of waiting. Sorry about that.

**Comment by kaspersorensen** [comment]
You can test it after the fact if you want then. It's released ;-)

**Pull request merged**
