### PR TITLE
Fix most of run n records cases (but there can still be slip-ups)

### LINKED ISSUE #1371: When using Execute with option 'Run first N records' all filters in the job are ignored
Originally submitted by @jacques-hi:

If a job contains one ore more filters, these are ignored when the job is executed with option 'Run first N records'.

### PR DESCRIPTION
**Pull request by LosD**
Unfiltered Analyzers might mean that too much data will be loaded.
Unfiltered transformers with results will _not_ be filtered.

Fixes #1371

I'm thinking I'd like to add a few test cases before merging.

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
LGTM!

**Comment by LosD** [comment]
Fixed existing unit tests.

**Comment by ClaudiaPHI** [comment]
Ready to merge ?

**Comment by LosD** [comment]
I'd say so. You want the honors?

**Pull request merged**
