### PR TITLE
Replaced the elasticsearch icon

### LINKED ISSUE #510: Replace Elasticsearch icons
Use the new icon image

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #510

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
screen shot 2015-07-16 at 1 42 12 pm

**Comment by ClaudiaPHI** [comment]
Please do not merge yet

**Comment by ClaudiaPHI** [comment]
The build passed :-). Merge !!

**Comment by kaspersorensen** [comment]
Would be better with transparent background.

**Comment by ClaudiaPHI** [comment]
screen shot 2015-07-16 at 4 57 51 pm
screen shot 2015-07-16 at 4 57 44 pm

**Comment by ClaudiaPHI** [comment]
Ready for merging

**Comment by kaspersorensen** [comment]
Looks good (nice even) to me :)

**Pull request merged**
