### PR TITLE
Issue #1786: Improved file textfield's resizing capabilities

### LINKED ISSUE #1786: Component config dialog requires resize to display file path on High-DPI screens
I've been using DataCleaner quite a bit recently on a high-dpi screen, and in general the tweaks we've applied works. Or at least they're mostly more good than not.

But there is one thing that really gets annoying: The component config dialogs for components such as "Write CSV file", or any other component that has a file property, don't display correctly. The file path text box is not shown unless you resize (enlarge) the window slightly. This should be fixed.

### PR DESCRIPTION
**Pull request by kaspersorensen**
Now resizing (specially making the window smaller) does not hide the text box used in a file selector:

image

Fixes #1786

### CODE REVIEW

**Comment by LosD** [comment]
That's... Pretty horrible. Really no way to doing this without going to a much more complex layout?

**Comment by kaspersorensen** [comment]
Maybe I could try with BoxLayout. But I'm sure the solution is to use another layout than FlowLayout. And then I just preferred GridBag because it has weights, so I could adjust how much to let the individual pieces influence the width of the thing.

The reason FlowLayout doesn't work for this type of widget is that it "wraps" components to the next line/flow vertically. So when you made the window smaller the parts started just disappearing because they where moved to an invisible line below.

**Comment by LosD** [comment]
Oh sure, flow layout is wrong, GridBagLayout is just such a nasty complicated layout for simple stuff. Not a blocker, though.

**Comment by kaspersorensen** [comment]
Heh, I tried with a `BoxLayout` and it works even better actually. So now it's simpler and if Travis doesn't complain, I suggest merging and then I'll open a vote for releasing.

**Comment by LosD** [comment]
Great! Travis happy, merging! :)

**Comment by zhangdw115** [comment]
When the explorer was quoted, it was found that the Chinese code could not be displayed.

**Pull request merged**
