### PR TITLE
Feature/bootstrap monitor ui

### LINKED ISSUE #1076: Uploading job or removing datastore in DC monitor shows json response
When uploading a job or removing a datastore in DC Monitor you leave the DC Monitor UI and your browser shows the json response of the REST call which was executed to either upload the job or remove the datastore, while you expect to return to the UI and have the job added or the datastore removed in your view.

### PR DESCRIPTION
**Pull request by kaspersorensen**
As I was playing around with the DC monitor today I started experimenting with applying the bootstrap CSS/JS framework to it in order to make it nicer to look at - and more consistent with the http://datacleaner.org website

The result is in this branch and is so far going quite well. But there is a small TODO list to be taken care of:

 - [x] Work more on the file upload widgets - there's no user feedback when he has browsed and selected a file.
 - [x] Remove irrelevant stuff from datacleaner-styles.css (copied from website codebase)
 - [x] Use bootstrap "btn" styles etc. on the GWT buttons (a _nice to have_ IMO).
 - [x] General cleanup - while working with this it seemed clear that there's a lot of pollution/legacy in the CSS files.

Fixes #1076

Anyways - on to the good parts! Some screenshots:

Login:

image

Datastores page:

image

Scheduling page:

image

Dashboard page:

image

Repository page:

image

### CODE REVIEW

**Comment by ClaudiaPHI** [comment]
:+1:

**Comment by kaspersorensen** [comment]
OK this PR is now ready to be reviewed and potentially merged.

Some notes though:

 * I experienced that the changes we had recently made to rewrite URLs and login redirection didn't work. That's why there are changes in security-context.xml and RewriteConfigurationProvider.
 * While testing the UI I also encountered some controllers that was not being resolved properly by spring. While fixing this (```CommonMvcConfig```) I also made some minor controller improvements - which actually fixes #1076 too! So I'll add that to the description.

Sorry for the many changed files in this PR - but the majority is just cosmetical stuff.

**Comment by kaspersorensen** [comment]
Updated the screenshots.

**Comment by kaspersorensen** [comment]
My own feedback after trying it a bit more:

 - [ ] The schedule anchors does not seem to have a "hand" cursor. Strange, but should be easy to fix.
 - [ ] In a few dialogs we have radio buttons (timeline chart visual options + job scheduling mode) and the margin (or padding or whatever) around those radio buttons seems to have gone haywire causing the text to overlap a bit.

**Comment by ClaudiaPHI** [comment]
Some notes from me: 

The text and images in the dialog for executing jobs are not centered 

image

image

**Pull request merged**
