### PR TITLE
Adding security headers to cookie retrieval request for CAS when comm…

### PR DESCRIPTION
**Pull request by MennoB**
…unicating with DataHub

### CODE REVIEW

**Comment by LosD** [comment]
Code (all one lines of it :)) looks good to me, but I know nothing about CAS.

I guess we can merge if/when Travis is happy.

**Comment by arjansh** [comment]
I also know nothing about CAS, but I see that you now apply the addSecurityHeaders method to both the `cookieRequest` variable and the `request` argument. Can you be certain that both these requests go to the same host and need the same security headers?

**Comment by MennoB** [comment]
@arjansh The headers contain the information that is necessary to get CAS authorisation. Every call needs to be verified by CAS, therefore every call will go through CAS first and for this it will need those same headers every time.

**Comment by arjansh** [comment]
LGTM then!

**Comment by LosD** [comment]
Okay, so I guess it is to make sure the payload (including HTTP headers) is the same?

**Comment by LosD** [comment]
Would it maybe be a good idea to check the response, so errors like this are caught?

**Comment by MennoB** [comment]
@LosD In the case of DataHub's CAS the ticket and user are relayed in the headers. So that's why they're necessary there. I can add a status code check for the cookie request, that might be useful.

**Comment by LosD** [comment]
Ah, makes sense.

Github doesn't send notifications when a commit is added, so if you make a comment when the check has been added, we'll react a bit faster :)

**Comment by MennoB** [comment]
Added a check for the status code when retrieving cookies. If we should fail harder here, please let me know.

**Comment by LosD** [comment]
Let's leave it like this for now... I'm not sure how stuff reacts on a hard failure, and the warning should at least help track down problems.

Merge when Travis is happy

**Comment by LosD** [comment]
Travis happy. Merging! :)

**Pull request merged**
