### PR TITLE
Align Eclipse formatter with IntelliJ

### PR DESCRIPTION
**Pull request by arjansh**
Changed eclipse code formatter so it formats the code more like Intellij does using the IDEA formatter.

Also added a few @formatter:off, @formatter:on annotations for some difficult cases.

### CODE REVIEW

**Comment by LosD** [comment]
@arjansh Do you want anyone to test it?

I can install an Eclipse and compare with my IntelliJ, but I'm not sure we'd get anything out of it, as the testing would be pretty random lookups, which we already did.

**Comment by arjansh** [comment]
@losd I think it would be nice if someone else using Eclipse starts using it, to double check that there are no corruptions introduced into the Formatter-Eclipse.xml. I don't think it is useful to directly apply it to all the code, because then we'll just encounter the same differences as before.

**Comment by LosD** [comment]
Agreed. I guess @ClaudiaPHI is the only non-you Eclipse user.

**Comment by ClaudiaPHI** [comment]
The build passes. LGTM!

**Pull request merged**
