### PR TITLE
JUNG graph API 2.1.1 upgrade

### PR DESCRIPTION
**Pull request by kaspersorensen**
This branch extends the branch used in PR #1788 - so please take a look at that one first.

This branch upgrades the JUNG library to the latest release (2.1.1). This release of JUNG now relies on Guava instead of the CERN collections library. Supposedly there are other improvements too, but mostly I just considered it a hygeine update and a chance to consolidate on less common libraries for lambdas etc..

### CODE REVIEW

**Comment by LosD** [comment]
Code LGTM, but Travis is angry (and I'm not sure why this PR isn't standalone. Basing it on #1788 doesn't seem to accomplish anything, it's just making review harder?)

**Comment by kaspersorensen** [comment]
I literally could not get the project compiling and running without #1788, so I thought it made sense to treat that as new "master" for my work.

I'll go and merge it - then it won't add noise anymore.

**Comment by LosD** [comment]
Oh, I though Java 10 would still work with an older source format.

How about the angry Travis? Unrelated?

**Comment by LosD** [comment]
Ah, checkstyle

**Comment by kaspersorensen** [comment]
Checkstyle fixed, and got the "LGTM" so I'm merging.

**Pull request merged**
