### PR TITLE
Yet another attempt to migrate away from Scala results

### LINKED ISSUE #1268: Scala deserialization exception for a job ran on Hadoop
I have ran the following job with Scatter plotter which is written in Scala: 

``` 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<job xmlns="http://eobjects.org/analyzerbeans/job/1.0">
    <job-metadata>
        <job-description>Created with DataCleaner Enterprise edition 5.0-SNAPSHOT</job-description>
        <author>claudiap</author>
        <updated-date>2016-03-31+02:00</updated-date>
        <metadata-properties>
            <property name="CoordinatesX.datacleaner.customers.csv">40</property>
            <property name="CoordinatesY.datacleaner.customers.csv">40</property>
        </metadata-properties>
    </job-metadata>
    <source>
        <data-context ref="customers.csv_2"/>
        <columns>
            <column id="col_id" path="id" type="STRING"/>
            <column id="col_given_name" path="given_name" type="STRING"/>
            <column id="col_family_name" path="family_name" type="STRING"/>
            <column id="col_company" path="company" type="STRING"/>
            <column id="col_address_line" path="address_line" type="STRING"/>
            <column id="col_post_code" path="post_code" type="STRING"/>
            <column id="col_city" path="city" type="STRING"/>
            <column id="col_country" path="country" type="STRING"/>
            <column id="col_email" path="email" type="STRING"/>
            <column id="col_birthdate" path="birthdate" type="STRING"/>
            <column id="col_gender" path="gender" type="STRING"/>
            <column id="col_job_title" path="job_title" type="STRING"/>
            <column id="col_income_amount" path="income_amount" type="STRING"/>
            <column id="col_income_currency" path="income_currency" type="STRING"/>
        </columns>
    </source>
    <transformation>
        <transformer name="Birthdate as date">
            <descriptor ref="Convert to date"/>
            <metadata-properties>
                <property name="CoordinatesX">360</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties>
                <property name="Time zone" value="Europe/Berlin"/>
                <property name="Null replacement" value="&lt;null&gt;"/>
                <property name="Date masks" value="[yyyy-MM-dd HH:mm:ss.S,yyyy-MM-dd HH:mm:ss,yyyy-MM-dd HH:mm,yyyyMMddHHmmssZ,yyMMddHHmmssZ,yyyy-MM-dd,yyyy.MM.dd,yyyy/MM/dd,dd-MM-yyyy,dd.MM.yyyy,dd/MM/yyyy,MM-dd-yyyy,MM.dd.yyyy,MM/dd/yyyy]"/>
            </properties>
            <input ref="col_birthdate"/>
            <output id="col_birthdateasdate" name="birthdate (as date)"/>
        </transformer>
        <transformer>
            <descriptor ref="Date to age"/>
            <metadata-properties>
                <property name="CoordinatesX">520</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties/>
            <input ref="col_birthdateasdate"/>
            <output id="col_ageindays" name="Age in days"/>
            <output id="col_ageinyears" name="Age in years"/>
        </transformer>
        <transformer name="Money amount as number">
            <descriptor ref="Convert to number"/>
            <metadata-properties>
                <property name="CoordinatesX">520</property>
                <property name="CoordinatesY">200</property>
            </metadata-properties>
            <properties>
                <property name="Decimal separator" value="&amp;#44;"/>
                <property name="Minus sign" value="-"/>
                <property name="Null replacement" value="&lt;null&gt;"/>
                <property name="Thousand separator" value="."/>
            </properties>
            <input ref="col_income_amount"/>
            <output id="col_income_amountasnumber" name="income_amount (as number)"/>
        </transformer>
    </transformation>
    <analysis>
        <analyzer name="Age in years vs income_amount (as number)">
            <descriptor ref="Scatter plot"/>
            <metadata-properties>
                <property name="CoordinatesX">680</property>
                <property name="CoordinatesY">120</property>
            </metadata-properties>
            <properties/>
            <input ref="col_gender" name="Group column"/>
            <input ref="col_ageinyears" name="Variable1"/>
            <input ref="col_income_amountasnumber" name="Variable2"/>
        </analyzer>
    </analysis>
</job>

 ``` 

The **exception** while trying to open the  result file: 

```
Unexpected error!
 
Message:
    java.io.InvalidClassException: scala.collection.immutable.$colon$colon; local class incompatible: stream classdesc serialVersionUID = -8476791151983527571, local class serialVersionUID = 509929039250432923
Level:
    SEVERE
Stack Trace:
scala.collection.immutable.$colon$colon; local class incompatible: stream classdesc serialVersionUID = -8476791151983527571, local class serialVersionUID = 509929039250432923
    java.io.ObjectStreamClass.initNonProxy(Unknown Source)
    java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
    java.io.ObjectInputStream.readClassDesc(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.defaultReadFields(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.readObject(Unknown Source)
    java.util.HashMap.readObject(Unknown Source)
    sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    java.lang.reflect.Method.invoke(Unknown Source)
    java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.defaultReadFields(Unknown Source)
    java.io.ObjectInputStream.readSerialData(Unknown Source)
    java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
    java.io.ObjectInputStream.readObject0(Unknown Source)
    java.io.ObjectInputStream.readObject(Unknown Source)
    org.datacleaner.actions.OpenAnalysisJobActionListener.openAnalysisResult(OpenAnalysisJobActionListener.java:144)
    
```
The problem seems to be that Hadoop is using other version of Scala.

### PR DESCRIPTION
**Pull request by LosD**
This latest attempt tries to leave almost everything but the actual results in place. Tests are almost untouched. Comments are more than welcome (needed, actually)

A common interface is made for all result classes, the old Scala classes are kept in place, but with their interfaces changed to match the interface. A new Java-based implementation is then added, and analyzers changed to use those. There are lots of conversions going on, but most of these should be relatively cheap, as a thin wrapper is used. The exception is the loaded compatibility classes, but those are only used for reading and the conversion is cached, so the cost should be acceptable.

Fixes #1268

Hopefully obsoletes #1294 and #1297 (But lets not remove the underlying branches just yet. Both have started moving the actual analyzers and renderers to Java, which we want to do soon-ish)

### CODE REVIEW

**Comment by LosD** [comment]
Okay, added last results types, and made deserialization work. The deserilization was was a bit of a bastard: We don't really support renaming classes with inner classes very well, and Scala makes a ton of them. In the end I had to give up on changing the name of the Scala ScatterGroup, and instead use a nasty like "CommonScatterGroup" for the interface. The problem seems to be that inner classes are named with the out class (i.e. the one I banged my head on was "ScatterGroup$$anonfun$1", which "ScalaScatterGroup$$anonfun$1" couldn't match). We have _some_ support in ChangeAwareObjectInputStream for that, but not enough.

For some reason, I also had to override the autogenerated serial id for that class, even though it wasn't necessary for the result classes. That worries me, so we may want to do pretty thorough testing.

@ClaudiaPHI You had all kinds of "nice" ways to break the original. Could I get you to unleash your destructive powers on this? :)

**Comment by ClaudiaPHI** [comment]
I will have a look

**Comment by LosD** [comment]
Aw man, this is bad. Apparently, interfaces are also serialized (I was stupid enough to assume that only  the concrete classes would actually be mentioned in the serialized data). That means that we _have_ to use a new name for everything.

I hate doing it, but I opted for prefixing with an I (i.e. IScatterAnalyzerResult).

I tried looking into the ChangeAwareObjectInputStream, but there seems to be no simple way to check if an ObjectStreamClass is an interface before trying to get the actual class from it, so I couldn't make a  test for that (by i.e. making a new `renamedConcreteClasses` map).

**Comment by ClaudiaPHI** [comment]
The tests pass on Hadoop. Ready to merge! :+1:

**Comment by LosD** [comment]
OHHHH YESSS!

**Pull request merged**
