### PR TITLE
Bug/1239 smaller set in preview

### LINKED ISSUE #1239: Preview should work on a smaller set for remote components
We should reduce the preview size for DataCloud components to a much smaller number like 10.

### PR DESCRIPTION
**Pull request by rposkocil**
Fixes #1239

### CODE REVIEW

**Comment by LosD** [comment]
Code LGTM, but is it possible to generalize this somehow without too much work? We have the same "costs money" issue with other transformers that can preview (admittedly not currently a lot, since the Satori services are implemented as analyzers), so it somehow seems wrong to make a special case of RemoteTransformer.

I'm thinking maybe a new annotation (`@DefaultPreviewSize(10)` or something like that).

It could also be something to be done for later.

**Comment by kaspersorensen** [comment]
I think the idea you have @losd is described in a bit more general terms in #170 - so I just wanted to add that as a remark :)

**Comment by kaspersorensen** [comment]
I'm merging this as a short term fix before the 5.0 release. I suggest to refactor it later while looking at the annotation API suggested in #170.

**Comment by LosD** [comment]
:+1:

**Pull request merged**
