### PR TITLE
Bug/1328 ordering of the components alphabetically

### LINKED ISSUE #1328: (No) alphabetic ordering of components
I just noticed that the components seem to no longer be alphabetically ordered in the menu/tree. This makes them a bit harder to find I think... 

image

I see this happening at least in the latest 5.0.2 release of DC.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #1328 

image

### CODE REVIEW

**Comment by LosD** [comment]
Did you find out what caused the original break of this?

**Comment by LosD** [comment]
(It used to be sorted, but all of a sudden it wasn't... But this looks like an entirely new implementation)

**Comment by ClaudiaPHI** [comment]
It never used to be sorted. I saw the issue long before Kasper saw it. Only the categories were sorted.

**Comment by LosD** [comment]
That is... not true:
image

(4.5.3)

**Comment by ClaudiaPHI** [comment]
I believe this is a simple coincidence of how the descriptors are loaded, but no specific ordering of descriptors was made in that class.

**Comment by LosD** [comment]
Pretty crazy coincidence

**Comment by jhorcicka** [comment]
While working on "remote components" I remember we had an issue with the order of components. It was different on various operating systems.

**Comment by LosD** [comment]
It may very well be a change in how the descriptors are presented (sorted vs unsorted), but it's not something random. _All_ of the components are sorted alphabetically, at least in 4.5.3.

That certainly doesn't make this fix incorrect in any way, I just don't like not knowing what happened.

**Comment by LosD** [comment]
We're both running Windows 7... Could it be Java version?

**Comment by LosD** [comment]
D'oh, now I'm being stupid, we're also both seeing it unordered in DC 5 :)

**Comment by LosD** [comment]
Wait, @ClaudiaPHI could it be that you saw it unordered in 4.5 when you were using the Mac?

**Comment by ClaudiaPHI** [comment]
It may be so. I remember I saw it long time a go, tried to find the cause, did not find it.

**Comment by LosD** [comment]
This is going to bother me forever :)

Oh well... This works, let's merge!

**Pull request merged**
