### PR TITLE
Feature/646 improve file dropzone to allow hdfs files

### LINKED ISSUE #646: Improve file dropzone to allow selection of HDFS files
Add a button next to the "(or click to browse)" button inside the dropzone to allow selecting/entering a HDFS resource path.

 - [x] The button should feature a small Hadoop (elefant) icon.
 - [x] Label should be "Select Hadoop HDFS file".
 - [x] The existing button should be relabeled to "Click to browse".
 - [x] When clicking the button we want to show the HDFS resource selector widget. Preferably inside the dropzone somehow - maybe replacing the position of the buttons.
 - [x] Once selected the automagic creation of datastore should function like/similar to selecting a normal local file.

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #646  

screen shot 2015-09-25 at 11 30 31 am

screen shot 2015-09-25 at 11 30 41 am

screen shot 2015-09-25 at 1 29 21 pm

### CODE REVIEW

**Comment by LosD** [comment]
The combobox probably shouldn't be there, one already elected to use HDFS.

**Comment by LosD** [comment]
Maybe also put the error below, so the input fields doesn't move aroud

**Comment by LosD** [comment]
Code looks good to me

**Comment by LosD** [comment]
Error doesn't seem related, it's the timeout @kaspersorensen was interested in:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.019 sec <<< FAILURE! - in org.datacleaner.test.full.scenarios.JobWithOutputDataStreamsTest
testSimpleBuildAndExecuteScenario(org.datacleaner.test.full.scenarios.JobWithOutputDataStreamsTest)  Time elapsed: 30.019 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.datacleaner.util.ConcurrencyUtils.awaitCountDown(ConcurrencyUtils.java:63)
	at org.datacleaner.job.concurrent.JobCompletionTaskListener.await(JobCompletionTaskListener.java:60)
	at org.datacleaner.job.runner.AnalysisResultFutureImpl.await(AnalysisResultFutureImpl.java:91)
	at org.datacleaner.test.full.scenarios.JobWithOutputDataStreamsTest.testSimpleBuildAndExecuteScenario(JobWithOutputDataStreamsTest.java:141)
```

**Comment by ClaudiaPHI** [comment]
Issues addressed: 

screen shot 2015-09-25 at 3 02 13 pm

**Comment by LosD** [comment]
LGTM!

**Comment by kaspersorensen** [comment]
Sorry this is coming too late, but a few small remarks on the UI side:
 * The elephant icon seems to be unequal width and height, making the resizing a bit off (out of scale).
 * I would like the button _next to_, not below the other button.

**Comment by ClaudiaPHI** [comment]
- It is difficult to obtain a square elephant. It does have a rather long nose :-P

**Comment by kaspersorensen** [comment]
hehehe right, but it should at least be in a square (maybe with some transparent padding) so that resizing to e.g. 16x16 pixels is harmless.

**Pull request merged**
