### PR TITLE
#1719 Colors were put into a properties file

### PR DESCRIPTION
**Pull request by jhorcicka**
Related to already closed issue #1719. 

Colors were put into a properties file (in the same manner as image paths).

### CODE REVIEW

**Comment by LosD** [comment]
Wow, that was a lot more that I expected! :)

I really like the rgba one, but I'm a bit worried about the `color.someothercolor` one. There's potential for endless loops here.

Since the end result (though probably not going to happen right now) is preferably to nuke any keys that has a specific color, I might be better to not have these references, and just use the same color (maybe with a comment like "same as `color.red`").

**Comment by LosD** [comment]
Hmmm... As we're not really going to use the ResourceBundles, as we talked about yesterday, you might instead want to make it into a utility class, probably somewhere outside oss-branding (or we'd have to copy it to any other branding class)

**Comment by LosD** [comment]
By the way, in CSS, they've deprecated rgba for rgb. You might (or might not) want to follow them.

> Note: In the CSS Color Module Level 4 spec, rgba() has been defined as a legacy function with identical grammar and behaviour to rgb(); in effect, an alias. Going forward, both can accept exactly the same parameters.

https://developer.mozilla.org/en/docs/Web/CSS/color_value#rgb

**Comment by jhorcicka** [comment]
I removed variables functionality in the properties file. Let's stop with additional improvements right now. Movement to a separate utility class can be done later and `rgba` => `rgb` as well. 

@LosD: Any other comments/remarks before merging?

**Comment by LosD** [comment]
Nope! Merging :)

**Pull request merged**
