### PR TITLE
Integration tests for sample jobs

### LINKED ISSUE #1577: Have desktop's jobs tested by integration tests
Jobs currently not available in Monitor by default but available in Desktop should be added into integration testing process. 

Relates to #1563

### PR DESCRIPTION
**Pull request by arjansh**
Fixes #1577.

Adds integration test for the nine sample jobs in DataCleaner which work out of the box. Runs the jobs in the same manner as the Command Line Interface.

### CODE REVIEW

**Comment by LosD** [comment]
LGTM, but a single consideration (that can easily be moved later, though).

**Comment by ClaudiaPHI** [comment]
LGTM!

**Comment by ClaudiaPHI** [comment]
The "Customer  age " job fails with: 
image

**Comment by ClaudiaPHI** [comment]
This test fails on my machine. I do not think we can merge it yet until #1589 is fixed.

**Comment by arjansh** [comment]
@ClaudiaPHI I don't think your test failure is caused by #1589, but by #1596. I made the test a little less strict (and added a TODO) to work around that issue.

**Comment by ClaudiaPHI** [comment]
LGTM! Tests pass

**Pull request merged**
